spring:
  application:
    name: zorvyn
  data:
    mongodb:
      uri: ${MONGODB_URI}  # Spring will look for an environment variable with this name
server:
  port: ${PORT:8081}     # Render provides a PORT variable; defaults to 8081 locally

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
